mensen:
  academica: https://www.studierendenwerk-aachen.de/speiseplaene/academica-w.html
  vita: https://www.studierendenwerk-aachen.de/speiseplaene/vita-w.html
  bayernallee: https://www.studierendenwerk-aachen.de/speiseplaene/bayernallee-w.html